"""Observation hook protocol (call sites wrapped in try/except, monitoring never blocks business)."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class StreamHooks(Protocol):
    """Stream observation hooks (injected by app side)."""

    async def on_stream_start(self, stream_id: str) -> None: ...
    async def on_first_token(self, stream_id: str, ttft: float) -> None: ...
    async def on_marker(self, stream_id: str, placeholder_id: str) -> None: ...
    async def on_resolved(self, stream_id: str, placeholder_id: str, elapsed: float) -> None: ...
    async def on_stream_end(self, stream_id: str, duration: float) -> None: ...
    async def on_error(self, stream_id: str, code: str, message: str) -> None: ...